### ISSUE TITLE
Excuse me, a go get problem

### ISSUE THREAD

**Issue by monaShe520** [edolphin-ydf/gopherlua-debugger#3]
When I went to go get, I encountered the following error, does the author have encountered it, if you have similar experience, I hope to inform; if not, then forget it, thanks
`go: github.com/edolphin-ydf/gopher-lua-debugger@v0.0.2: reading github.com/edolphin-ydf/gopher-lua-debugger/go.mod at revision v0.0.2: unknown revision v0.0.2`

**Comment by edolphin-ydf** [comment]
I'v tried go get with version, and have the same error with you. 
But after i run `go get github.com/edolphin-ydf/gopherlua-debugger`, it upgrade to v0.0.2 atomaticly. Then run `go get github.com/edolphin-ydf/gopher-lua-debugger@v0.0.2`, there is no error anymore. 
I don't know why and you can just use `go get github.com/edolphin-ydf/gopherlua-debugger`.
