### ISSUE TITLE
Why hook be implemented as a LFunction instead of a simple go function?

### ISSUE THREAD

**Issue by myrfy001** [edolphin-ydf/gopherlua-debugger#4]
Why the hook is push onto the Lua Stack and then called by `L.callR()` in `hook.go`?  Why not simply call a go function with current LState as param?

**Comment by edolphin-ydf** [comment]
In c lua, the hook not only work in c, but also in lua.
And here, only implement go support currently. But with this implementation, it's easy to extend to lua.

And this should be an issue in gopherlua, for anyone maybe confused, this [link](https://github.com/edolphin-ydf/gopher-lua/blob/b8b10300367ae75736adc6f557bca1f330833127/hook.go#L22) is a transport.
