### ISSUE TITLE
Breakpoints not working in GoLand

### ISSUE THREAD

**Issue by KDing0** [edolphin-ydf/gopherlua-debugger#9]
![EmmyDebug](https://user-images.githubusercontent.com/38357906/109438174-07eaac80-7a29-11eb-95ea-de92022fcaab.png)
Hi
I'm having trouble getting the breakpoints to work even in the test files provided by this project in the testlua folder.
The program seems to connect to the debugger server provided by EmmyLua but the breakpoints aren't triggered.

Here are the steps I took:
- I installed EmmyLua via the GoLand IDE Plugins section. 
- I copied the project files from your GitHub page.
- I checked to make sure that go.mod had the replace line in it.
- I checked to make sure that the testlua files have the `lua_debugger.Preload(L)` line.
- I configured the EmmyLua Debugger in the Debug Configurations Build and ran it (See the screenshot for the configuration)
- I ran the main.go file in testlua by using `go run main.go` in the terminal

The result:
- The program connects to the debugger `Server(localhost:9966) open successfully, wait for connection...
Connected.`
- The program executes, but no breakpoints are triggered.

**Comment by edolphin-ydf** [comment]
Did you make a breakpoint in the lua source like this ?
![image](https://user-images.githubusercontent.com/4330411/109447589-fdf39880-7a7e-11eb-91de-cf50aaaddaa9.png)

Or could you upload a project that can reproduce this issue?

**Comment by KDing0** [comment]
Yes, I'm using the test files provided by this project to test if it works and I set a breakpoint. A video of me doing so is attached to this post. Also ill attach the project files just in case in a zip.
[gopherlua-debugger.zip](https://github.com/edolphin-ydf/gopherlua-debugger/files/6060928/gopherlua-debugger.zip)

https://user-images.githubusercontent.com/38357906/109486825-aa377e00-7a83-11eb-8419-b3793f9fda6c.mp4

**Comment by edolphin-ydf** [comment]
Thanks for the issue. I'v made a new version v0.03, please try it. If there still exist any issue, just tell me.

**Comment by KDing0** [comment]
I tested your updated version in both the test files and on the project I'm working on, and it seems to be working properly now in both, thank you very much!
